[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "raytracer_lib"
path = "src/lib.rs"

[dependencies]
nalgebra = "0.32.4"
tobj = "4.0.1"
